name: Commit
on: push

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - uses: extenda/actions/gcp-secret-manager@v0
        with:
          service-account-key: ${{ secrets.SECRET_AUTH }}
          secrets: |
            DOCKER_PASSWORD: dockerhub-password
            DOCKER_USERNAME: dockerhub-username

      - uses: actions/setup-node@v1
        with:
          node-version: 13

      - name: Run tests
        run: |
          npm ci
          npm ci --prefix commitlint-plugin-tense
          npm test --prefix commitlint-plugin-tense

      - name: Push to DockerHub
        if: github.ref == 'refs/heads/master'
        uses: extenda/actions/docker@v0
        with:
          image: extenda/commitlint
          tag: latest
          registry: docker.io
          dockerfile: Dockerfile
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}
